name: Microsoft Rewards Farmer

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Google Chrome 97.0.4692.71
      run: |
         echo -e "\033[0;35m********** Removing unsupported version and downloading supported version of Google Chrome **********\033[0m"
         {
            sudo apt-get purge google-chrome-stable -y
            wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_97.0.4692.71-1_amd64.deb
         } &> /dev/null
         sudo dpkg -i google-chrome-stable_97.0.4692.71-1_amd64.deb
         sudo apt-mark hold google-chrome-stable
    - name: Chromedriver 97.0.4692.71,
      run: |
         sudo apt install unzip -y
         echo -e "\033[0;36m********** Downloading Google Chrome Webdriver **********\033[0m"
         {
            wget https://chromedriver.storage.googleapis.com/97.0.4692.71/chromedriver_linux64.zip
         } &> /dev/null
         sudo unzip chromedriver_linux64.zip chromedriver -d /usr/local/bin -y
    - name: Farming Points
      run: |
         python ms_rewards_farmer.py --fast --headless --on-finish exit --telegram YOUR_BOT_TOKEN YOUR_CHAT_ID

    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.config/google-chrome
        key: ${{ runner.os }}-build-${{ hashFiles('**~/.config/google-chrome') }}
        restore-keys: |
          ${{ runner.os }}-build-